<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="PRATIK" failures="1" tests="6" name="personal loan" time="0.11" errors="0" timestamp="2023-02-05T00:04:41 IST">
  <testcase classname="testNG.Ploan" name="demo1" time="0.015"/>
  <testcase classname="testNG.Ploan" name="demo2" time="0.002"/>
  <testcase classname="testNG.Ploan" name="pLoan" time="0.006"/>
  <testcase classname="testNG.day1" name="demo" time="0.002"/>
  <testcase classname="testNG.day1" name="failTest" time="0.008">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testNG.day1.failTest(day1.java:41)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- failTest -->
  <testcase classname="testNG.day1" name="secondTest" time="0.002"/>
</testsuite> <!-- personal loan -->
